# Dockerfile for DEV environment, we will come back to look into production environment later.

FROM node:10-slim

# Need this to make jest --watch work from container
# see: https://github.com/zushenyan/docker-jest-issue/tree/successful_build
RUN apt-get update -qq
RUN apt-get install -y build-essential
RUN apt-get install -y git

# WORKDIR /usr/app

COPY package.json .
COPY package-lock.json .
RUN npm install --quiet

ENV NODE_ENV development
ENV PORT 8080

COPY . .